### ISSUE TITLE
Renommer le script pour permettre une installation plus facile.

### ISSUE THREAD

**Issue by N-Mi** [Orken/HFR-Leboncoin-preview#1]
Pour que Greasemonkey propose d'installer automatiquement le script en cliquant sur un lien (par exemple celui de ta signature), il faut que :
- le nom du fichier se termine par `.user.js`
- le serveur ne renvoie pas un content-type `text/html`

Je propose donc de renommer `hfr-leboncoin-preview.js` en `hfr-leboncoin-preview.user.js` (et évidemment de modifier ta signature en conséquence).

Pour tester, j'ai mis ton script sur un serveur web local et j'ai fait cette manip, et Greasemonkey m'a bien ouvert une fenêtre d'installation pour le script.

**Comment by Orken** [comment]
J'étais justement en train de chercher pourquoi ça ne m'ouvrait pas la fenetre d'install. Merci :jap:

**Comment by N-Mi** [comment]
J'ai désinstallé le script et appelé la nouvelle URL, ça marche nickel maintenant.

Merci :jap:
